### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by kinow** [niwa/dusty-acorn#11]
Hey @guolivar , would it be all right if I ported the code to Python 3?

It would involve changing the directory structure, as well as some code. I can do that in my spare time, and should be done in a few days. Python2 is end of life in less than 10 months, and we now have Tornado 6 (latest).

Cheers
Bruno

**Comment by guolivar** [comment]
Yes, go ahead if you can!
Let me know if you need/want help.

**Comment by kinow** [comment]
Thanks! Will definitely need help with testing, or maybe if I can't remember why we did something in the code (hopefully there will be some comments and good git messages from my past self :)

Pull requests coming in in the next days.

Cheers
Bruno
